version: '3'
services:
  db:
    image: postgres
    container_name: kn_db
    networks:
      - kn-bridge
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: kn_admin
      POSTGRES_DB: kn_wallets

  app:
    image: vrfvitor/knwallets
    container_name: kn_app
    networks:
      - kn-bridge
    depends_on:
      - db
    ports:
      - 8080:8080

networks:
  kn-bridge:
    driver: bridge