spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:kn_db}:${DB_PORT:5432}/${DB_NAME:kn_wallets}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWD:kn_admin}

server:
  servlet:
    context-path: /api
